export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const USER_LOGOUT = 'USER_LOGOUT'

export const ALERT_DANGER = 'ALERT_DANGER'
export const ALERT_INFO = 'ALERT_INFO'
export const ALERT_WARNING = 'ALERT_WARNING'